---
- name: "{{ service_name }} restart"
  become: true
  shell: systemctl daemon-reload
  notify: "{{ service_name }} restart service"

- name: "{{ service_name }} restart service"
  become: true
  service:
    name: "{{ service_name }}"
    state: restarted
    enabled: yes
  notify: handler_exit

- name: "{{ service_name }} restart uninstall"
  become: true
  shell: systemctl daemon-reload
  notify: reset-failed

- name: reset-failed
  become: true
  shell: systemctl reset-failed
  notify: handler_exit

- name: handler_exit
  debug:
    msg: DONE
